src/Entity/Oauth.php
<?php

namespace App\Entity;

use App\Repository\OauthRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OauthRepository::class)
 */
class Oauth
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity=User::class, cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $code;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $access_token;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $refresh_token;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $expiration_date;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(?string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getAccessToken(): ?string
    {
        return $this->access_token;
    }

    public function setAccessToken(?string $access_token): self
    {
        $this->access_token = $access_token;

        return $this;
    }

    public function getRefreshToken(): ?string
    {
        return $this->refresh_token;
    }

    public function setRefreshToken(?string $refresh_token): self
    {
        $this->refresh_token = $refresh_token;

        return $this;
    }

    public function getExpirationDate(): ?\DateTimeInterface
    {
        return $this->expiration_date;
    }

    public function setExpirationDate(?\DateTimeInterface $expiration_date): self
    {
        $this->expiration_date = $expiration_date;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Controller/OauthController.php
<?php

namespace App\Controller;

use App\Entity\ImageLog;
use App\Entity\Oauth;
use App\Repository\ImageLogRepository;
use App\Service\Google;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

class OauthController extends AbstractController
{
    /**
     * @var Google
     */
    private $google;

    public function __construct(Google $google)
    {
        $this->google = $google;
    }
    /**
     * @Route("/oauth", name="oauth_php")
     */
    public function index()
    {
        $oauth = $this->getDoctrine()->getRepository(Oauth::class)->findOneBy([
            'user' => $this->getUser()->getId()
        ]);

        return $this->render('oauth/index.html.twig', [
            'title' => 'Отримання доступу',
            'oauth' => $oauth,
            'current_date' => new \DateTime(),
            'request_url' => $this->getRequestUrl(),
        ]);
    }

    /**
     * @Route("oauth/code", name="get_token")
     * @param Request $request
     * @throws \App\Exception\InvalidTokenException
     */
    public function getToken(Request $request)
    {
        $code = $request->get('code');
        if (!empty($code)) {
            $this->log('Отримано новий код доступу.', ['code' => $code]);
            try {
                $tokens = $this->google->getToken(
                    $code,
                    $this->getParameter('google_client_id'),
                    $this->getParameter('google_client_secret'),
                    $this->generateUrl('get_token', [], UrlGeneratorInterface::ABSOLUTE_URL)
                );

                $this->getDoctrine()->getRepository(Oauth::class)->upsert($tokens, $this->getUser(), $code);

                $this->log('Отримано новий токен.', $tokens);
            } catch (\Exception $exception) {
                $this->log('Не вдалось отримати токен.', ['error' => $exception->getMessage()]);
            }
        }
        return $this->redirect($this->generateUrl('oauth_php'));
    }

    /**
     * @Route("oauth/log", name="oauth_log")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function imageLog(Request $request)
    {
        /**
         * @var ImageLogRepository $imageLogRepository
         */
        $page = (int) $request->get('page', 1);
        $limit = (int) $request->get('limit', 30);
        $imageLogRepository = $this->getDoctrine()->getRepository(ImageLog::class);

        $totalCount = (int) $imageLogRepository->getTotalCount();
        $list = $imageLogRepository->paginate($page, $limit);
        return $this->render('oauth/list.html.twig', [
            'title' => 'Історія запитів',
            'list' => $list,
            'totalPages' => ceil($totalCount/$limit),
            'page' => $page,
            'limit' => $limit
            ]);
    }

    private function log($message, $description)
    {
        $em = $this->getDoctrine()->getManager();
        $imageLog = new ImageLog();
        $imageLog->setMessage($message)
            ->setUser($this->getUser())
            ->setCreatedAt(new \DateTime())
            ->setDescription($description);
        $em->persist($imageLog);
        $em->flush($imageLog);
    }

    private function getRequestUrl()
    {
        return "https://accounts.google.com/o/oauth2/v2/auth?" .
            "client_id=" . $this->getParameter('google_client_id') .
            "&response_type=code" .
            "&scope=https://www.googleapis.com/auth/photoslibrary" .
            "&redirect_uri=" . $this->generateUrl('get_token', [], UrlGeneratorInterface::ABSOLUTE_URL) .
            "&access_type=offline";
    }
}

templates/oauth/index.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <div class="oauth-desc">Ви підтверджуєте доступ до ваших фотографій в google photo. Натисніть на кнопку "Відкрити доступ" та у вспливаючому вікні підтвердіть свою дію.</div>
    <div>
        {% if oauth %}
            <div>Токен було отримано: {{ oauth.createdAt|date('d.m.Y H:i:s') }}</div>
            <div>Токен закінчується: {{ oauth.expirationDate|date('d.m.Y H:i:s') }}</div>
        {% else %}
            <div class="bold">Токен ще не отримано.</div>
        {% endif %}
    </div>
    <div class="center">
        <a href="{{ request_url }}" class="oauth_link">
            {% if oauth and oauth.expirationDate > current_date %}
                Оновини токен
            {% else %}
                Відкрити доступ
            {% endif %}
        </a>
    </div>
    <div>
        <a href="{{ path('oauth_log') }}">Переглянути історію</a>
    </div>
{% endblock %}

templates/oauth/list.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <table class="datagrid">
        <thead>
            <tr>
                <th>№</th>
                <th>Повідомлення</th>
                <th>Деталі</th>
                <th>Дата</th>
            </tr>
        </thead>
        <tbody>
            {% if (list|length) %}
                {% for key, item in list %}
                <tr>
                    <td>{{ key+1 }}</td>
                    <td>{{ item.message }}</td>
                    <td>
                        <table>
                        {% for description_key, description_item in item.description %}
                            <tr>
                                <td>{{ description_key }}</td>
                                <td>{{ description_item }}</td>
                            </tr>
                        {% endfor %}
                        </table>
                    </td>
                    <td>{{ item.created_at.format('d.m.Y H:i:s') }}</td>
                </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="4">Поки що немає жодних повідомлень.</td>
                </tr>
            {% endif %}
        </tbody>
    </table>
    {% include 'common/pagination.html.twig' with {
        currentFilters: [],
        currentPage: page,
        paginationPath: "oauth_log",
        lastPage: totalPages,
        showAlwaysFirstAndLast: true
    } only %}
{% endblock %}