src/Entity/Image.php
<?php

namespace App\Entity;

use App\Repository\ImageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\UniqueConstraint;

/**
 * @ORM\Entity(repositoryClass=ImageRepository::class)
 * @ORM\Table(name="image", uniqueConstraints={@UniqueConstraint(name="google_id", columns={"google_id"})})
 */
class Image
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $filename;

    /**
     * @ORM\Column(type="text")
     */
    private $path;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $downloaded_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cameraMake;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cameraModel;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $focalLength;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $apertureFNumber;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $isoEquivalent;

    /**
     * @ORM\Column(type="integer")
     */
    private $width;

    /**
     * @ORM\Column(type="integer")
     */
    private $height;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $google_id;

    /**
     * @ORM\ManyToMany(targetEntity=Album::class, inversedBy="images")
     */
    private $album;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $locked_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $local_path;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $processed_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $deleted;

    public function __construct()
    {
        $this->album = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(string $filename): self
    {
        $this->filename = $filename;

        return $this;
    }

    public function getPath(): ?string
    {
        return $this->path;
    }

    public function setPath(string $path): self
    {
        $this->path = $path;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getDownloadedAt(): ?\DateTimeInterface
    {
        return $this->downloaded_at;
    }

    public function setDownloadedAt(\DateTimeInterface $downloaded_at): self
    {
        $this->downloaded_at = $downloaded_at;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getCameraMake(): ?string
    {
        return $this->cameraMake;
    }

    public function setCameraMake(?string $cameraMake): self
    {
        $this->cameraMake = $cameraMake;

        return $this;
    }

    public function getCameraModel(): ?string
    {
        return $this->cameraModel;
    }

    public function setCameraModel(?string $cameraModel): self
    {
        $this->cameraModel = $cameraModel;

        return $this;
    }

    public function getFocalLength(): ?float
    {
        return $this->focalLength;
    }

    public function setFocalLength(?float $focalLength): self
    {
        $this->focalLength = $focalLength;

        return $this;
    }

    public function getApertureFNumber(): ?float
    {
        return $this->apertureFNumber;
    }

    public function setApertureFNumber(?float $apertureFNumber): self
    {
        $this->apertureFNumber = $apertureFNumber;

        return $this;
    }

    public function getIsoEquivalent(): ?int
    {
        return $this->isoEquivalent;
    }

    public function setIsoEquivalent(?int $isoEquivalent): self
    {
        $this->isoEquivalent = $isoEquivalent;

        return $this;
    }

    public function getWidth(): ?int
    {
        return $this->width;
    }

    public function setWidth(int $width): self
    {
        $this->width = $width;

        return $this;
    }

    public function getHeight(): ?int
    {
        return $this->height;
    }

    public function setHeight(int $height): self
    {
        $this->height = $height;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getGoogleId(): ?string
    {
        return $this->google_id;
    }

    public function setGoogleId(string $google_id): self
    {
        $this->google_id = $google_id;

        return $this;
    }

    /**
     * @return Collection|Album[]
     */
    public function getAlbum(): Collection
    {
        return $this->album;
    }

    public function addAlbum(Album $album): self
    {
        if (!$this->album->contains($album)) {
            $this->album[] = $album;
        }

        return $this;
    }

    public function removeAlbum(Album $album): self
    {
        if ($this->album->contains($album)) {
            $this->album->removeElement($album);
        }

        return $this;
    }

    public function getLockedAt(): ?\DateTimeInterface
    {
        return $this->locked_at;
    }

    public function setLockedAt(?\DateTimeInterface $locked_at): self
    {
        $this->locked_at = $locked_at;

        return $this;
    }

    public function getLocalPath(): ? string
    {
        return $this->local_path;
    }

    public function setLocalPath(string $localPath): self
    {
        $this->local_path = $localPath;
        return $this;
    }

    public function getProcessedAt(): ?\DateTimeInterface
    {
        return $this->processed_at;
    }

    public function setProcessedAt(?\DateTimeInterface $processed_at): self
    {
        $this->processed_at = $processed_at;

        return $this;
    }

    public function getDeleted(): ?bool
    {
        return $this->deleted;
    }

    public function setDeleted(bool $deleted): self
    {
        $this->deleted = $deleted;

        return $this;
    }
}

src/Controller/ImageController.php
<?php

namespace App\Controller;

use App\Entity\Image;
use App\Repository\ImageRepository;
use App\Service\DownloaderService;
use App\Service\ProcessImageService;
use App\Service\RemoveImageService;
use Doctrine\Common\Collections\Criteria;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

class ImageController extends AbstractController
{
    const MAX_LOCKING_TIME = 10; //seconds

    /**
     * @var DownloaderService
     */
    private $downloaderService;

    /**
     * @var RemoveImageService
     */
    private $removeImageService;

    /**
     * @var ProcessImageService
     */
    private $processImageService;

    public function __construct(
        DownloaderService $downloaderService,
        RemoveImageService $removeImageService,
        ProcessImageService $processImageService
    )
    {
        $this->downloaderService = $downloaderService;
        $this->removeImageService = $removeImageService;
        $this->processImageService = $processImageService;
    }

    /**
     * List of all users
     *
     * @Route("/images", name="images")
     */
    public function index(Request $request): Response
    {
        /**
         * @var ImageRepository $imagesRepository
         */
        $imagesRepository = $this->getDoctrine()->getRepository(Image::class);
        $perPage = $request->get('per_page', 100);
        $page = (int) $request->get('page', 1);
        $search = $request->get('q');
        $filters = ['q' => $search];

        if ($page < 1) {
            $page = 1;
        }
        $criteria = Criteria::create();
        $criteria->where(Criteria::expr()->eq("deleted", 0));

        if (!empty($search)) {
            $criteria->andWhere(Criteria::expr()->contains("description", $search));
        }
        $totalCount = $imagesRepository->total($criteria);

        $maxPage = ceil($totalCount/$perPage);

        if ($maxPage) {
            if ($page > $maxPage) {
                $page = $maxPage;
            }
            $images = $imagesRepository->getImagesPerPage($page, $perPage, $criteria);
        } else {
            $images = [];
        }
        return $this->render(
            'images/index.html.twig',
            [
                'title' => 'Фотографії',
                'images' => $images,
                'total' => $totalCount,
                'filtervariables' => $filters,
                'page' => $page,
                'perPage' => $perPage,
                'totalPages' => $maxPage
            ]
        );
    }

    /**
     * Edit Image
     *
     * @Route("/images/{id}", requirements={"id"="\d+"}, name="image-edit", methods={"POST"})
     */
    public function edit(Request $request): JsonResponse
    {
        $imageId = $request->get('id');
        $image = $this->getDoctrine()->getRepository(Image::class)->find($imageId);
        if (empty($image)) {
            throw new NotFoundHttpException('Фото не існує, або було видалене.');
        }

        $description = $request->get('description');

        if (!empty($description)) {
            $image->setDescription($description);
        }

        $em = $this->getDoctrine()->getManager();
        $em->persist($image);
        $em->flush();
        return new JsonResponse(['ok']);
    }

    /**
     * Delete image
     *
     * @Route("/images/delete/{id}", requirements={"id"="\d+"}, name="image-delete")
     */
    public function softDelete(Request $request): JsonResponse
    {
        $imageId = $request->get('id');
        /**
         * @var Image $image
         */
        $image = $this->getDoctrine()->getRepository(Image::class)->find($imageId);
        if (empty($image)) {
            throw new NotFoundHttpException('Фото не існує, або було видалене.');
        }

        $localPath = $this->removeImageService->remove($image);

        $image->setDeleted(true);
        $image->setLocalPath($localPath);

        $em = $this->getDoctrine()->getManager();
        $em->persist($image);
        $em->flush();
        return new JsonResponse(['ok']);
    }

    /**
     * Make image active again
     *
     * @Route("/images/revoke/{id}", requirements={"id"="\d+"}, name="image-revoke")
     */
    public function revoke(Request $request): JsonResponse
    {
        $imageId = $request->get('id');
        /**
         * @var Image $image
         */
        $image = $this->getDoctrine()->getRepository(Image::class)->find($imageId);
        if (empty($image)) {
            throw new NotFoundHttpException('Фото не існує, або було видалене.');
        }

        $localPath = $this->removeImageService->revoke($image);

        $image->setDeleted(false);
        $image->setLocalPath($localPath);
        $this->processImageService->resize($image);

        $em = $this->getDoctrine()->getManager();
        $em->persist($image);
        $em->flush();
        return new JsonResponse(['ok']);
    }
}

templates/images/edit.html.twig
<div class="image-edit-container">
    <div class="close-button"><i class="fas fa-window-close"></i></div>
    <form action="{{ path('image-edit', {id: image.id}) }}" class="image-edit-form">
        <textarea name="description" placeholder="Опис">{{ image.description }}</textarea>
        <div class="">Дата зйомки: {{ image.createdAt | date("d.m.Y H:i:s")  }}</div>
        <div class="">Категорія: </div>
        <div class="">Завантажено: {{ image.downloadedAt | date("d.m.Y H:i:s") }}</div>
        <div class="">Розміри: {{ image.width }} x {{ image.height }}</div>
        <div class="">Камера: {{ image.cameraMake }} {{ image.cameraModel}} </div>
        <div class="">Фокальна відстань: {{ image.focalLength }}</div>
        <div class="">Діафрагма: {{ image.apertureFnumber }}</div>
        <div class="">ISO: {{ image.isoEquivalent }}</div>
        <div class="">Google id: {{ image.googleId }}</div>
        <input type="hidden" name="id" value="{{ image.id }}">
        <button>Зберегти</button>
    </form>
</div>

templates/images/index.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <div id="images">
        <h2>Фото</h2>
        {% include 'common/pagination.html.twig' with {
            currentFilters: filtervariables,
            currentPage: page,
            paginationPath: "images",
            lastPage: totalPages,
            showAlwaysFirstAndLast: true
        } only %}
        <div class="image-filters">
            <form method="get" action="{{ path('images') }}" class="quick-search">
                <input type="text" placeholder="Опис у фото" value="{{ filtervariables.q }}" name="q">
                <button type="submit"><i class="fas fa-search"></i></button>
            </form>
        </div>
            {% for key, image in images %}
                {% include 'images/single-image.html.twig' with {
                    image:image,
                    page:page,
                    perPage:perPage
                } only
                %}
            {% else %}
                <div class="no-results">Нема фотографій</div>
            {% endfor %}
        </div>
        {% include 'common/pagination.html.twig' with {
            currentFilters: filtervariables,
            currentPage: page,
            paginationPath: "images",
            lastPage: totalPages,
            showAlwaysFirstAndLast: true
        } only %}
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('js/images') }}
{% endblock %}

templates/images/single-image.html.twig
<div class="image-container">
    <img src="thumbnail/{{ image.localPath }}" style="{{ (image.height > image.width) ? "max-width" : "max-height" }}: 100%" data-width="{{ image.width }}" data-height="{{ image.height }}" data-delete="{{ path('image-delete', {id: image.id}) }}"  data-revoke="{{ path('image-revoke', {id: image.id}) }}">
    {% include 'images/edit.html.twig' with {
        image:image
    } only
    %}
    <i class="fas fa-redo image-remove-icon"></i>
</div>